!***********************************************************************
!                           NEC2D_IO.F90
!***********************************************************************
!
!     Input/Output Subroutines for NEC2D - MODERNIZED
!
!     Phase 2 Modernization Complete:
!     ✓ Free-form Fortran 90 format  
!     ✓ All 20 GOTO statements eliminated
!     ✓ Modern DO...END DO loops (no statement labels)
!     ✓ Structured control flow
!     • Kept IMPLICIT REAL*8 for COMMON block compatibility
!     • Kept COMMON blocks (convert to modules in Phase 4)
!
!***********************************************************************

SUBROUTINE READGM(INUNIT,CODE,I1,I2,R1,R2,R3,R4,R5,R6,R7)
  ! READGM reads a geometry record and parses it.
  IMPLICIT REAL*8(A-H,O-Z)
  CHARACTER*(*) CODE
  DIMENSION INTVAL(2), REAVAL(7)

  CALL PARSIT(INUNIT,2,7,CODE,INTVAL,REAVAL,IEOF)

  IF (IEOF < 0) CODE = 'GE'
  I1 = INTVAL(1)
  I2 = INTVAL(2)
  R1 = REAVAL(1)
  R2 = REAVAL(2)
  R3 = REAVAL(3)
  R4 = REAVAL(4)
  R5 = REAVAL(5)
  R6 = REAVAL(6)
  R7 = REAVAL(7)

END SUBROUTINE READGM


SUBROUTINE READMN(INUNIT,CODE,I1,I2,I3,I4,F1,F2,F3,F4,F5,F6)
  ! READMN reads a control record and parses it.
  IMPLICIT REAL*8(A-H,O-Z)
  CHARACTER*(*) CODE
  DIMENSION INTVAL(4), REAVAL(6)

  CALL PARSIT(INUNIT,4,6,CODE,INTVAL,REAVAL,IEOF)

  IF (IEOF < 0) CODE = 'EN'
  I1 = INTVAL(1)
  I2 = INTVAL(2)
  I3 = INTVAL(3)
  I4 = INTVAL(4)
  F1 = REAVAL(1)
  F2 = REAVAL(2)
  F3 = REAVAL(3)
  F4 = REAVAL(4)
  F5 = REAVAL(5)
  F6 = REAVAL(6)

END SUBROUTINE READMN


SUBROUTINE PARSIT(INUNIT,MAXINT,MAXREA,CMND,INTFLD,REAFLD,IEOF)
  ! PARSIT reads an input record and parses it.
  ! MODERNIZED: Eliminated 3 GOTOs (143, 175, 190)
  IMPLICIT REAL*8(A-H,O-Z)
  CHARACTER NGFNAM*80
  COMMON /NGFNAM/NGFNAM
  CHARACTER CMND*2, BUFFER*20, REC*80
  INTEGER INTFLD(MAXINT)
  INTEGER BGNFLD(12), ENDFLD(12), TOTCOL, TOTFLD
  LOGICAL FLDTRM
  DIMENSION REAFLD(MAXREA)

  READ(INUNIT, 8000, IOSTAT=IEOF) REC
  CALL UPCASE(REC, REC, TOTCOL)

  ! Store opcode and clear field arrays
  CMND = REC(1:2)
  DO I = 1, MAXINT
    INTFLD(I) = 0
  END DO
  DO I = 1, MAXREA
    REAFLD(I) = 0.0D0
  END DO
  DO I = 1, 12
    BGNFLD(I) = 0
    ENDFLD(I) = 0
  END DO

  ! Find field boundaries
  TOTFLD = 0
  FLDTRM = .FALSE.
  LAST = MAXREA + MAXINT
  DO J = 3, TOTCOL
    K = ICHAR(REC(J:J))
    
    IF (K == 33) THEN  ! End of line comment '!'
      IF (FLDTRM) ENDFLD(TOTFLD) = J - 1
      EXIT  ! ELIMINATED GO TO 5000
    ELSE IF (K == 32 .OR. K == 44) THEN  ! Space or comma
      IF (FLDTRM) THEN
        ENDFLD(TOTFLD) = J - 1
        FLDTRM = .FALSE.
      END IF
    ELSE IF (.NOT. FLDTRM) THEN
      TOTFLD = TOTFLD + 1
      FLDTRM = .TRUE.
      BGNFLD(TOTFLD) = J
    END IF
  END DO

  IF (FLDTRM) ENDFLD(TOTFLD) = TOTCOL

  ! Check field limits
  IF ((CMND == 'WG') .OR. (CMND == 'GF')) THEN
    NGFNAM = 'NGF2D.NEC'
  END IF

  IF (TOTFLD == 0) THEN
    RETURN
  ELSE IF (TOTFLD > LAST) THEN
    WRITE(*,8001)
    WRITE(*,8004) REC
    STOP 'CARD ERROR'  ! ELIMINATED GO TO 9010
  END IF

  J = MIN(TOTFLD, MAXINT)

  ! Parse integers
  DO I = 1, J
    LENGTH = ENDFLD(I) - BGNFLD(I) + 1
    BUFFER = REC(BGNFLD(I):ENDFLD(I))
    IF (((CMND == 'WG') .OR. (CMND == 'GF')) .AND. &
        (BUFFER(1:1) /= '0') .AND. (BUFFER(1:1) /= '1')) THEN
      NGFNAM = REC(BGNFLD(I):ENDFLD(I))
      RETURN
    END IF
    IND = INDEX(BUFFER(1:LENGTH), '.')
    IF (IND > 0 .AND. IND < LENGTH) THEN  ! ELIMINATED GO TO 9000
      WRITE(*,8002) I
      WRITE(*,8004) REC
      STOP 'CARD ERROR'
    END IF
    IF (IND == LENGTH) LENGTH = LENGTH - 1
    READ(BUFFER(1:LENGTH), *, ERR=9000) INTFLD(I)
  END DO

  ! Parse reals  
  IF (TOTFLD > MAXINT) THEN
    J = MAXINT + 1
    DO I = J, TOTFLD
      LENGTH = ENDFLD(I) - BGNFLD(I) + 1
      BUFFER = REC(BGNFLD(I):ENDFLD(I))
      IND = INDEX(BUFFER(1:LENGTH), '.')
      IF (IND == 0) THEN
        INDE = INDEX(BUFFER(1:LENGTH), 'E')
        LENGTH = LENGTH + 1
        IF (INDE == 0) THEN
          BUFFER(LENGTH:LENGTH) = '.'
        ELSE
          BUFFER = BUFFER(1:INDE-1) // '.' // BUFFER(INDE:LENGTH-1)
        END IF
      END IF
      READ(BUFFER(1:LENGTH), *, ERR=9100) REAFLD(I-MAXINT)
    END DO
  END IF
  RETURN

  ! Error handling
9000 WRITE(*,8002) I
  WRITE(*,8004) REC
  STOP 'CARD ERROR'

9100 I = I - MAXINT
  WRITE(*,8003) I
  WRITE(*,8004) REC
  STOP 'CARD ERROR'

8000 FORMAT (A80)
8001 FORMAT (//,' ***** CARD ERROR - TOO MANY FIELDS IN RECORD')
8002 FORMAT (//,' ***** CARD ERROR - INVALID NUMBER AT INTEGER POSITION ',I1)
8003 FORMAT (//,' ***** CARD ERROR - INVALID NUMBER AT REAL POSITION ',I1)
8004 FORMAT (' ***** TEXT -->  ',A80)

END SUBROUTINE PARSIT


SUBROUTINE UPCASE(INTEXT, OUTTXT, LENGTH)
  ! UPCASE converts text to upper case.
  IMPLICIT REAL*8(A-H,O-Z)
  CHARACTER*(*) INTEXT, OUTTXT

  LENGTH = LEN(INTEXT)
  DO I = 1, LENGTH
    J = ICHAR(INTEXT(I:I))
    IF (J >= 96) J = J - 32
    OUTTXT(I:I) = CHAR(J)
  END DO

END SUBROUTINE UPCASE


SUBROUTINE PRNT(IN1,IN2,IN3,FL1,FL2,FL3,FL4,FL5,FL6,CTYPE)
  ! PRNT prints impedance loading data.
  IMPLICIT REAL*8(A-H,O-Z)
  CHARACTER CTYPE*(*), CINT(3)*5, CFLT(6)*13

  DO I = 1, 3
    CINT(I) = '     '
  END DO

  IF (IN1 == 0 .AND. IN2 == 0 .AND. IN3 == 0) THEN
    CINT(1) = '  ALL'
  ELSE
    IF (IN1 /= 0) WRITE(CINT(1),90) IN1
    IF (IN2 /= 0) WRITE(CINT(2),90) IN2
    IF (IN3 /= 0) WRITE(CINT(3),90) IN3
  END IF

  DO I = 1, 6
    CFLT(I) = '     '
  END DO

  IF (ABS(FL1) > 1.E-30) WRITE(CFLT(1),91) FL1
  IF (ABS(FL2) > 1.E-30) WRITE(CFLT(2),91) FL2
  IF (ABS(FL3) > 1.E-30) WRITE(CFLT(3),91) FL3
  IF (ABS(FL4) > 1.E-30) WRITE(CFLT(4),91) FL4
  IF (ABS(FL5) > 1.E-30) WRITE(CFLT(5),91) FL5
  IF (ABS(FL6) > 1.E-30) WRITE(CFLT(6),91) FL6
  WRITE(*,92) (CINT(I),I=1,3), (CFLT(I),I=1,6), CTYPE

90 FORMAT(I5)
91 FORMAT(1P,E13.4)
92 FORMAT(/,3X,3A,3X,6A,3X,A)

END SUBROUTINE PRNT


SUBROUTINE GFIL(IPRT)
  ! GFIL reads the N.G.F. file.
  ! MODERNIZED: Eliminated 8 GOTOs (30/31, 337, 358, 385/388, 390, 395, 402, 412)
  IMPLICIT REAL*8(A-H,O-Z)
  PARAMETER (MAXSEG=3000, MAXMAT=3000)
  PARAMETER (LOADMX=MAXSEG/10)
  PARAMETER (NSMAX=120)
  PARAMETER (NETMX=240)
  PARAMETER (JMAX=60)
  PARAMETER (IRESRV=MAXMAT**2)
  COMPLEX*16 CM,SSX,ZRATI,ZRATI2,T1,ZARRAY,AR1,AR2,AR3,EPSCF,FRATI
  COMMON /DATA/ X(MAXSEG),Y(MAXSEG),Z(MAXSEG),SI(MAXSEG),BI(MAXSEG), &
    ALP(MAXSEG),BET(MAXSEG),WLAM,ICON1(2*MAXSEG),ICON2(2*MAXSEG), &
    ITAG(2*MAXSEG),ICONX(MAXSEG),LD,N1,N2,N,NP,M1,M2,M,MP,IPSYM
  COMMON /CMB/ CM(IRESRV)
  COMMON /ANGL/ SALP(MAXSEG)
  COMMON /GND/ZRATI,ZRATI2,FRATI,T1,T2,CL,CH,SCRWL,SCRWR,NRADL, &
    KSYMP,IFAR,IPERF
  COMMON /GGRID/ AR1(11,10,4),AR2(17,5,4),AR3(9,8,4),EPSCF,DXA(3),DYA(3), &
    XSA(3),YSA(3),NXA(3),NYA(3)
  COMMON /MATPAR/ ICASE,NBLOKS,NPBLK,NLAST,NBLSYM,NPSYM,NLSYM,IMAT, &
    ICASX,NBBX,NPBX,NLBX,NBBL,NPBL,NLBL
  COMMON /SMAT/ SSX(16,16)
  COMMON /ZLOAD/ ZARRAY(MAXSEG),NLOAD,NLODF
  COMMON/SAVE/EPSR,SIG,SCRWLT,SCRWRT,FMHZ,IP(2*MAXSEG),KCOM
  COMMON/CSAVE/COM(19,5)
  CHARACTER NGFNAM*80
  COMMON /NGFNAM/NGFNAM
  DIMENSION T2X(1),T2Y(1),T2Z(1)
  EQUIVALENCE (T2X,ICON1),(T2Y,ICON2),(T2Z,ITAG)
  DATA IGFL/20/
  LOGICAL FILE_EXISTS

  ! Check file exists (ELIMINATED GO TO 30/31)
  INQUIRE(FILE=NGFNAM, EXIST=FILE_EXISTS)
  IF (.NOT. FILE_EXISTS) THEN
    WRITE(*,*) 'ERROR: Cannot open NGF file'
    STOP
  END IF
  OPEN(UNIT=IGFL,FILE=NGFNAM,FORM='UNFORMATTED',STATUS='OLD')
  REWIND IGFL

  READ (IGFL) N1,NP,M1,MP,WLAM,FMHZ,IPSYM,KSYMP,IPERF,NRADL,EPSR,SIG, &
              SCRWLT,SCRWRT,NLODF,KCOM
  N = N1
  M = M1
  N2 = N1 + 1
  M2 = M1 + 1

  ! Read segment data (ELIMINATED GO TO 2)
  IF (N1 > 0) THEN
    READ (IGFL) (X(I),I=1,N1),(Y(I),I=1,N1),(Z(I),I=1,N1)
    READ (IGFL) (SI(I),I=1,N1),(BI(I),I=1,N1),(ALP(I),I=1,N1)
    READ (IGFL) (BET(I),I=1,N1),(SALP(I),I=1,N1)
    READ (IGFL) (ICON1(I),I=1,N1),(ICON2(I),I=1,N1)
    READ (IGFL) (ITAG(I),I=1,N1)
    IF (NLODF /= 0) READ (IGFL) (ZARRAY(I),I=1,N1)
    DO I = 1, N1
      XI = X(I)*WLAM
      YI = Y(I)*WLAM
      ZI = Z(I)*WLAM
      DX = SI(I)*0.5D0*WLAM
      X(I) = XI - ALP(I)*DX
      Y(I) = YI - BET(I)*DX
      Z(I) = ZI - SALP(I)*DX
      SI(I) = XI + ALP(I)*DX
      ALP(I) = YI + BET(I)*DX
      BET(I) = ZI + SALP(I)*DX
      BI(I) = BI(I)*WLAM
    END DO
  END IF

  ! Read patch data (ELIMINATED GO TO 4)
  IF (M1 > 0) THEN
    J = LD - M1 + 1
    READ (IGFL) (X(I),I=J,LD),(Y(I),I=J,LD),(Z(I),I=J,LD)
    READ (IGFL) (SI(I),I=J,LD),(BI(I),I=J,LD),(ALP(I),I=J,LD)
    READ (IGFL) (BET(I),I=J,LD),(SALP(I),I=J,LD)
    READ (IGFL) (T2X(I),I=J,LD),(T2Y(I),I=J,LD)
    READ (IGFL) (T2Z(I),I=J,LD)
    DX = WLAM*WLAM
    DO I = J, LD
      X(I) = X(I)*WLAM
      Y(I) = Y(I)*WLAM
      Z(I) = Z(I)*WLAM
      BI(I) = BI(I)*DX
    END DO
  END IF

  READ (IGFL) ICASE,NBLOKS,NPBLK,NLAST,NBLSYM,NPSYM,NLSYM,IMAT
  IF (IPERF == 2) READ (IGFL) AR1,AR2,AR3,EPSCF,DXA,DYA,XSA,YSA,NXA,NYA
  NEQ = N1 + 2*M1
  NPEQ = NP + 2*MP
  NOP = NEQ/NPEQ
  IF (NOP > 1) READ (IGFL) ((SSX(I,J),I=1,NOP),J=1,NOP)
  READ (IGFL) (IP(I),I=1,NEQ),COM

  ! Read matrix (ELIMINATED GO TO 5/10 and computed GO TO)
  IF (ICASE <= 2) THEN
    IOUT = NEQ*NPEQ
    READ (IGFL) (CM(I),I=1,IOUT)
  ELSE
    REWIND 13
    IF (ICASE == 4) THEN
      IOUT = NPEQ*NPEQ
      DO K = 1, NOP
        READ (IGFL) (CM(J),J=1,IOUT)
        WRITE (13) (CM(J),J=1,IOUT)
      END DO
    ELSE
      IOUT = NPSYM*NPEQ*2
      NBL2 = 2*NBLSYM
      DO IOP = 1, NOP
        DO I = 1, NBL2
          CALL BLCKIN(CM,IGFL,1,IOUT,1,206)
          CALL BLCKOT(CM,13,1,IOUT,1,205)
        END DO
      END DO
    END IF
    REWIND 13
  END IF

  REWIND IGFL

  ! Write heading
  WRITE(*,16)
  WRITE(*,14)
  WRITE(*,14)
  WRITE(*,17)
  WRITE(*,18) N1, M1
  IF (NOP > 1) WRITE(*,19) NOP
  WRITE(*,20) IMAT, ICASE

  ! (ELIMINATED GO TO 11)
  IF (ICASE >= 3) THEN
    NBL2 = NEQ*NPEQ
    WRITE(*,21) NBL2
  END IF

  WRITE(*,22) FMHZ
  IF (KSYMP == 2 .AND. IPERF == 1) WRITE(*,23)
  IF (KSYMP == 2 .AND. IPERF == 0) WRITE(*,27)
  IF (KSYMP == 2 .AND. IPERF == 2) WRITE(*,28)
  IF (KSYMP == 2 .AND. IPERF /= 1) WRITE(*,24) EPSR, SIG
  WRITE(*,17)

  DO J = 1, KCOM
    WRITE(*,15) (COM(I,J),I=1,19)
  END DO

  WRITE(*,17)
  WRITE(*,14)
  WRITE(*,14)
  WRITE(*,16)

  IF (IPRT == 0) RETURN

  WRITE(*,25)
  DO I = 1, N1
    WRITE(*,26) I,X(I),Y(I),Z(I),SI(I),ALP(I),BET(I)
  END DO

14 FORMAT (5X,50H**************************************************, &
           34H**********************************)
15 FORMAT (5X,3H** ,19A4,3H **)
16 FORMAT (////)
17 FORMAT (5X,2H**,80X,2H**)
18 FORMAT (5X,29H** NUMERICAL GREEN'S FUNCTION,53X,2H**,/, &
           5X,17H** NO. SEGMENTS =,I4,10X,13HNO. PATCHES =,I4,34X,2H**)
19 FORMAT (5X,27H** NO. SYMMETRIC SECTIONS =,I4,51X,2H**)
20 FORMAT (5X,34H** N.G.F. MATRIX -  CORE STORAGE =,I7, &
           23H COMPLEX NUMBERS,  CASE,I2,16X,2H**)
21 FORMAT (5X,2H**,19X,13HMATRIX SIZE =,I7,16H COMPLEX NUMBERS,25X,2H**)
22 FORMAT (5X,14H** FREQUENCY =,1P,E12.5,5H MHZ.,51X,2H**)
23 FORMAT (5X,17H** PERFECT GROUND,65X,2H**)
24 FORMAT (5X,44H** GROUND PARAMETERS - DIELECTRIC CONSTANT =,1P, &
           E12.5,26X,2H**,/,5X,2H**,21X,14HCONDUCTIVITY =,E12.5, &
           8H MHOS/M.,25X,2H**)
25 FORMAT (39X,31HNUMERICAL GREEN'S FUNCTION DATA,/, &
           41X,27HCOORDINATES OF SEGMENT ENDS,/,51X,8H(METERS),/, &
           5X,4HSEG.,11X,19H- - - END ONE - - -,26X, &
           19H- - - END TWO - - -,/,6X,3HNO.,6X,1HX,14X,1HY,14X,1HZ, &
           14X,1HX,14X,1HY,14X,1HZ)
26 FORMAT (1X,I7,1P,6E15.6)
27 FORMAT (5X,55H** FINITE GROUND.  REFLECTION COEFFICIENT APPROXIMATION, &
           27X,2H**)
28 FORMAT (5X,38H** FINITE GROUND.  SOMMERFELD SOLUTION,44X,2H**)

END SUBROUTINE GFIL


SUBROUTINE GFOUT
  ! GFOUT writes the N.G.F. file.
  ! MODERNIZED: Eliminated 8 GOTOs (500/507, 525/528, 529/536, 539/547)
  IMPLICIT REAL*8(A-H,O-Z)
  PARAMETER (MAXSEG=3000, MAXMAT=3000)
  PARAMETER (LOADMX=MAXSEG/10)
  PARAMETER (NSMAX=120)
  PARAMETER (NETMX=240)
  PARAMETER (JMAX=60)
  PARAMETER (IRESRV=MAXMAT**2)
  COMPLEX*16 CM,SSX,ZRATI,ZRATI2,T1,ZARRAY,AR1,AR2,AR3,EPSCF,FRATI
  COMMON /DATA/ X(MAXSEG),Y(MAXSEG),Z(MAXSEG),SI(MAXSEG),BI(MAXSEG), &
    ALP(MAXSEG),BET(MAXSEG),WLAM,ICON1(2*MAXSEG),ICON2(2*MAXSEG), &
    ITAG(2*MAXSEG),ICONX(MAXSEG),LD,N1,N2,N,NP,M1,M2,M,MP,IPSYM
  COMMON /CMB/ CM(IRESRV)
  COMMON /ANGL/ SALP(MAXSEG)
  COMMON /GND/ZRATI,ZRATI2,FRATI,T1,T2,CL,CH,SCRWL,SCRWR,NRADL, &
    KSYMP,IFAR,IPERF
  COMMON /GGRID/ AR1(11,10,4),AR2(17,5,4),AR3(9,8,4),EPSCF,DXA(3),DYA(3), &
    XSA(3),YSA(3),NXA(3),NYA(3)
  COMMON /MATPAR/ ICASE,NBLOKS,NPBLK,NLAST,NBLSYM,NPSYM,NLSYM,IMAT, &
    ICASX,NBBX,NPBX,NLBX,NBBL,NPBL,NLBL
  COMMON /SMAT/ SSX(16,16)
  COMMON /ZLOAD/ ZARRAY(MAXSEG),NLOAD,NLODF
  COMMON/SAVE/EPSR,SIG,SCRWLT,SCRWRT,FMHZ,IP(2*MAXSEG),KCOM
  COMMON/CSAVE/COM(19,5)
  CHARACTER NGFNAM*80
  COMMON /NGFNAM/NGFNAM
  DIMENSION T2X(1),T2Y(1),T2Z(1)
  EQUIVALENCE (T2X,ICON1),(T2Y,ICON2),(T2Z,ITAG)
  DATA IGFL/20/

  OPEN(UNIT=IGFL,FILE=NGFNAM,FORM='UNFORMATTED',STATUS='UNKNOWN')
  NEQ = N + 2*M
  NPEQ = NP + 2*MP
  NOP = NEQ/NPEQ
  WRITE (IGFL) N,NP,M,MP,WLAM,FMHZ,IPSYM,KSYMP,IPERF,NRADL,EPSR, &
               SIG,SCRWLT,SCRWRT,NLOAD,KCOM

  ! Write segment data (ELIMINATED GO TO 1)
  IF (N > 0) THEN
    WRITE (IGFL) (X(I),I=1,N),(Y(I),I=1,N),(Z(I),I=1,N)
    WRITE (IGFL) (SI(I),I=1,N),(BI(I),I=1,N),(ALP(I),I=1,N)
    WRITE (IGFL) (BET(I),I=1,N),(SALP(I),I=1,N)
    WRITE (IGFL) (ICON1(I),I=1,N),(ICON2(I),I=1,N)
    WRITE (IGFL) (ITAG(I),I=1,N)
    IF (NLOAD > 0) WRITE (IGFL) (ZARRAY(I),I=1,N)
  END IF

  ! Write patch data (ELIMINATED GO TO 2)
  IF (M > 0) THEN
    J = LD - M + 1
    WRITE (IGFL) (X(I),I=J,LD),(Y(I),I=J,LD),(Z(I),I=J,LD)
    WRITE (IGFL) (SI(I),I=J,LD),(BI(I),I=J,LD),(ALP(I),I=J,LD)
    WRITE (IGFL) (BET(I),I=J,LD),(SALP(I),I=J,LD)
    WRITE (IGFL) (T2X(I),I=J,LD),(T2Y(I),I=J,LD)
    WRITE (IGFL) (T2Z(I),I=J,LD)
  END IF

  WRITE (IGFL) ICASE,NBLOKS,NPBLK,NLAST,NBLSYM,NPSYM,NLSYM,IMAT
  IF (IPERF == 2) WRITE (IGFL) AR1,AR2,AR3,EPSCF,DXA,DYA,XSA,YSA,NXA,NYA
  IF (NOP > 1) WRITE (IGFL) ((SSX(I,J),I=1,NOP),J=1,NOP)
  WRITE (IGFL) (IP(I),I=1,NEQ),COM

  ! Write matrix (ELIMINATED GO TO 3/12 and computed GO TO)
  IF (ICASE <= 2) THEN
    IOUT = NEQ*NPEQ
    WRITE (IGFL) (CM(I),I=1,IOUT)
  ELSE IF (ICASE == 4) THEN
    REWIND 13
    I = NPEQ*NPEQ
    DO K = 1, NOP
      READ (13) (CM(J),J=1,I)
      WRITE (IGFL) (CM(J),J=1,I)
    END DO
    REWIND 13
  ELSE
    REWIND 13
    REWIND 14
    IF (ICASE /= 5) THEN
      IOUT = NPBLK*NEQ*2
      DO I = 1, NBLOKS
        CALL BLCKIN(CM,13,1,IOUT,1,201)
        CALL BLCKOT(CM,IGFL,1,IOUT,1,202)
      END DO
      DO I = 1, NBLOKS
        CALL BLCKIN(CM,14,1,IOUT,1,203)
        CALL BLCKOT(CM,IGFL,1,IOUT,1,204)
      END DO
    ELSE
      IOUT = NPSYM*NPEQ*2
      DO IOP = 1, NOP
        DO I = 1, NBLSYM
          CALL BLCKIN(CM,13,1,IOUT,1,205)
          CALL BLCKOT(CM,IGFL,1,IOUT,1,206)
        END DO
        DO I = 1, NBLSYM
          CALL BLCKIN(CM,14,1,IOUT,1,207)
          CALL BLCKOT(CM,IGFL,1,IOUT,1,208)
        END DO
      END DO
    END IF
    REWIND 13
    REWIND 14
  END IF

  REWIND IGFL
  WRITE(*,13) IGFL, IMAT

13 FORMAT (///,44H ****NUMERICAL GREEN'S FUNCTION FILE ON TAPE,I3, &
           5H****,/,5X,16HMATRIX STORAGE -,I7,16H COMPLEX NUMBERS,///)

END SUBROUTINE GFOUT


SUBROUTINE BLCKOT(AR,NUNIT,IX1,IX2,NBLKS,NEOF)
  ! BLCKOT controls writing of matrix blocks.
  IMPLICIT REAL*8(A-H,O-Z)
  COMPLEX*16 AR
  DIMENSION AR(1)

  I1 = (IX1 + 1) / 2
  I2 = (IX2 + 1) / 2
  WRITE (NUNIT) (AR(J),J=I1,I2)

END SUBROUTINE BLCKOT


SUBROUTINE BLCKIN(AR,NUNIT,IX1,IX2,NBLKS,NEOF)
  ! BLCKIN controls reading of matrix blocks.
  ! MODERNIZED: Converted from ENTRY to separate subroutine, eliminated label-sharing
  IMPLICIT REAL*8(A-H,O-Z)
  COMPLEX*16 AR
  DIMENSION AR(1)

  I1 = (IX1 + 1) / 2
  I2 = (IX2 + 1) / 2

  DO I = 1, NBLKS
    READ (NUNIT,END=3) (AR(J),J=I1,I2)
  END DO
  RETURN

3 WRITE(*,4) NUNIT, NBLKS, NEOF
  IF (NEOF /= 777) STOP
  NEOF = 0

4 FORMAT (13H  EOF ON UNIT,I3,9H  NBLKS= ,I3,8H  NEOF= ,I5)

END SUBROUTINE BLCKIN


SUBROUTINE REBLK(B,BX,NB,NBX,N2C)
  ! REBLK reblocks array in N.G.F. solution.
  IMPLICIT REAL*8(A-H,O-Z)
  COMPLEX*16 B,BX
  COMMON /MATPAR/ ICASE,NBLOKS,NPBLK,NLAST,NBLSYM,NPSYM,NLSYM,IMAT, &
    ICASX,NBBX,NPBX,NLBX,NBBL,NPBL,NLBL
  DIMENSION B(NB,1), BX(NBX,1)

  REWIND 16
  NIB = 0
  NPB = NPBL

  DO IB = 1, NBBL
    IF (IB == NBBL) NPB = NLBL
    REWIND 14
    NIX = 0
    NPX = NPBX

    DO IBX = 1, NBBX
      IF (IBX == NBBX) NPX = NLBX
      READ (14) ((BX(I,J),I=1,NPX),J=1,N2C)
      DO I = 1, NPX
        IX = I + NIX
        DO J = 1, NPB
          B(IX,J) = BX(I,J+NIB)
        END DO
      END DO
      NIX = NIX + NPBX
    END DO

    WRITE (16) ((B(I,J),I=1,NB),J=1,NPB)
    NIB = NIB + NPBL
  END DO

  REWIND 14
  REWIND 16

END SUBROUTINE REBLK
